version: '3' 

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.1
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dimension2
      - MYSQL_PASSWORD=dimension2
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 80:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always