#!/bin/bash
yum install epel-release -y && yum install git wget -y && yum update -y
yum remove docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-selinux \
                  docker-engine-selinux \
                  docker-engine -y
				  
yum install -y yum-utils \
  device-mapper-persistent-data \
  lvm2 -y
  
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
	
yum install docker-ce -y
systemctl enable docker.service
systemctl start docker.service
docker login
