#!/bin/bash

aptitude update && aptitude safe-upgrade -y && apt-get update

apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic test"

apt install docker-ce

docker run hello-world
