#!/bin/bash

apt-get install software-properties-common -y
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db
add-apt-repository 'deb [arch=amd64,i386] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.1/debian jessie main'

apt-get update
apt-get install mariadb-server mariadb-client

mysql_upgrade -uroot
systemctl restart mariadb.service
mysql -V
