#!/bin/bash

apt update && apt install fio sysbench stress-ng stress -y

stress-ng --cpu 4 --vm 2 --vm-bytes 75% --io 2 --timeout 120s --metrics-brief && sysbench cpu --cpu-max-prime=20000 run && sysbench memory --memory-total-size=2G run
