#!/bin/bash

apt update && apt upgrade -y && apt install git wget calc net-tools software-properties-common aptitude dirmngr whois dnsutils vim iperf3 nodejs npm -y && aptitude update && aptitude safe-upgrade -y && apt autoremove -y
