version: '3'  

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nextcloud-letsencrypt
    depends_on:
      - proxy
    restart: unless-stopped

  db:
    image: mariadb:10.2
    container_name: nextcloud-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped

  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    depends_on:
      - letsencrypt
      - proxy
      - db
    environment:
      - VIRTUAL_HOST=nextcloud.rcapaul.ch
      - LETSENCRYPT_HOST=nextcloud.rcapaul.ch
      - LETSENCRYPT_EMAIL=roge.capaul@rcapaul.ch
    restart: unless-stopped