version: '3'
services:
    php-apache:
        image: php:7.2-fpm
        container_name: php_web
        depends_on:
          - mariadb
        volumes:
          - d:/html/:/var/www/html/
        ports:
            - 80:80

    mariadb:
        image: mariadb:10.2
        environment:
            TZ: "Europe/Zurich"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "dimension2"
            MYSQL_USER: 'roge'
            MYSQL_PASSWORD: 'dimension2'
            MYSQL_DATABASE: 'testdb'
        ports:
          - "3306:3306"
