version: '3'
services:
  mariadb:
          image: mariadb:10.2
          environment:
            TZ: Europe/Zurich
            MYSQL_ROOT_PASSWORD: dimension2
            MYSQL_USER: root
            MYSQL_PASSWORD: dimension2
            MYSQL_DATABASE: testdb
        ports:
          - "3306:3306"
  php-apache:
          image: php:7.2-apache
          container_name: php_web
          depends_on:
            - mariadb
          volumes:
            - d:/html/:/var/www/html/
          ports:
            - 80:80