version: '3'
services:
    php-apache:
        image: php:7.2-fpm
        ports:
            - 80:80
        links:
            - 'mariadb'

    mariadb:
        image: mariadb:10.1
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "dimension2"
            MYSQL_USER: 'roge'
            MYSQL_PASSWORD: 'dimension2'
            MYSQL_DATABASE: 'testdb'
