version: '3'

services:
  mariadb:
        build: ../../mariadb-10.2/.
        environment:
            TZ: Europe/Zurich
        restart: always
        ports:
          - "3306:3306"
  php-apache:
        image: php:7.2-apache
        container_name: php_web
        depends_on:
            - mariadb
        volumes:
            - ./:/var/www/html/
        restart: always
        ports:
            - "80:80"