version: "3"
services:
  your_app:
    depends_on:
      - your_app-letsencrypt
  your_app-letsencrypt:
    image: linuxserver/letsencrypt
    container_name: your_app-letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/letsencrypt:/config
    environment:
      - EMAIL=monitoring.hosttech@gmail.com
      - URL=rogecapaul.ch
      - SUBDOMAINS=www,api
      - VALIDATION=http
      - TZ=Europe/Zurich
      - PUID=0
      - PGID=0